### ISSUE TITLE
零碎的

### ISSUE THREAD

**Issue by itboos** [itboos/accumulation#10]
1.  
document.querySelector("#22");  
这个将导致错误：
VM188:1 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#01test' is not a valid selector.
    at <anonymous>:1:10
对于css 2:
该值在元素的主子树中的所有ID中必须是唯一的，并且必须至少包含一个字符。该值不能包含任何空格字符。

**身份证可以采用什么形式没有其他限制; 特别是，ID可以只包含数字，以数字开头，以下划线开头，仅包含标点符号等。**

### 但是，querySelector方法使用CSS3选择器来查询DOM，CSS3不支持以数字开头的ID选择器：
在CSS中，标识符（包括元素名称，类和选择器中的ID）只能包含字符[a-zA-Z0-9]和ISO 10646字符U + 00A0及更高版本，以及连字符（ - ）和下划线_）; 他们不能以数字，两个连字符或连字符后跟数字开头。

使用类似于b22ID属性的值，并且您的代码将起作用。

**Comment by itboos** [comment]
### input 输入框默认调起数字键盘的方法:
描述: 在用户输入手机号和验证码时，我们希望仅仅是调起九宫格的数字键盘
```html
  <input type="number" class="phone-input"   placeholder="请输入手机号" v-model="tell">
```
但是上面的那种写法， 安卓上是数字键盘， 但是在IOS 上，还是会看到文字（逼死强迫症）
解决办法:
方法1：
 利用html 5 ，input type = 'phone'  这样写，ios和安卓调起的都是默认只有 数字键盘
```html
  <input type="phone" class="phone-input"   placeholder="请输入手机号" v-model="tell">
```
方法2： 在type = number 的输入框上加上 正则，pattern="\d*"
```html
  <input type="number" class="phone-input" pattern="\d*"  placeholder="请输入手机号" v-model="tell">
```
参考链接:
[html5 input框默认调用九宫格数字键盘](http://jay1943000.is-programmer.com/posts/95139.html)
[论如何优雅的在手机端 input 框输入数字](https://blog.yongyuan.us/articles/2016-09-06-type-number)

**Comment by itboos** [comment]
###  关于input不同type值的样式重
[关于input不同type值的样式重](https://blog.csdn.net/wjnf012/article/details/72773130)

**Comment by itboos** [comment]
[qrcode-js生成二维码](https://github.com/davidshimjs/qrcodejs)

**Comment by itboos** [comment]
```css
  // 阻止a 链接跳转：
 // e.preventDefault, herf = "#"

 a[href="http://example.com"] {
   pointer-events: none;
 }
```
[pointer-events](https://developer.mozilla.org/zh-CN/docs/Web/CSS/pointer-events)

**Comment by itboos** [comment]
###  input 输入框无法输入的问题
问题描述： Pc端可以获得焦点，移动端无法获得焦点，也无法输入
原因： 
css 样式里：
```css
  * {
     box-sizing: border-box;
    /*禁用文字选中*/
    -webkit-touch-callout:none;
    -webkit-user-select:none;
    user-select:none;
    -webkit-tap-highlight-color: rgba(0,0,0,0);
}
```
其中，禁止了所有元素选中的， 这使得input 也无法选中，导致无法输入

解决办法：
使input 可以选中，
设置：
``` css
   input {
       -webkit-user-select: auto;
        user-select: auto;
   }
```

**Comment by itboos** [comment]
[禁止蒙层底部页面跟随滚动](https://segmentfault.com/a/1190000012313337?_ea=2953311)
```
   自己遇到的情况， 顶部 tabBar 固定, 中间内容自动滚动，没有设置高度
   当打开弹窗蒙层时， 中间内容设置成高度 100%， overflow: hidden
```

**Comment by itboos** [comment]
一个请求的截图：
![image](https://user-images.githubusercontent.com/21290640/53625706-c9a23300-3c3e-11e9-901d-b55d9b3f282a.png)

**Comment by itboos** [comment]
### 单行文本和多行文本溢出显示省略号
_单行文本溢出显示省略号,元素有时需要设置宽度_
```css
    .one-line{
       overflow: hidden;
       text-overflow: ellipsis;
       white-space: nowrap;
    }
```
下面的方法对部分浏览器无效
```css
.m-ellipsis {
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 3; // 行数
  -webkit-box-orient: vertical;  
}
```
### React中多行文本省略失效问题

![image](https://user-images.githubusercontent.com/21290640/53731090-a97ba980-3eb4-11e9-9cef-d43fd9760329.png)

```
<div className="desc m-ellipsis" style={{"WebkitBoxOrient": "vertical"}}>{props.description}</div>
```
